### ISSUE TITLE
Can't find new releases

### ISSUE THREAD

**Issue by matthughes** [cquiroz/scalajs-react-clipboard#14]
I can't seem to find any of the newer releases past 0.5.2 in a Nexus repo anywhere.  Did they actually get published?  Coming from 0.5.1, I was looking for a version that supported the latest ScalaJS React.

**Comment by cquiroz** [comment]
I changed the groupid to `io.github.cquiroz.react` maybe that is the problem? the README should be updated

**Comment by cquiroz** [comment]
and the package name is `react-clipboard` rather than the longish `scalajs-react-clipboard`. The README is now fixed
